name: Verification Tests

on:
  push:
  schedule:
    - cron: '47 * * * *'

jobs:
  away:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Python prerequisites
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

      # set up a secret called CREDENTIALS_JSON_BASE64 and set it to the value
      #   of `base64 -i ./credentials.json`
    - name: Set credentials
      run: |
        echo "${{ secrets.CREDENTIALS_JSON_BASE64 }}" | base64 -d > credentials.json
    - name: Check for DMs and send away message if necessary
      run: python ./away.py
